# Generated by Django 5.0.9 on 2024-10-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_cta_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
    ]
