# Generated by Django 5.0.9 on 2024-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepageimagebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimagebanner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
