# Generated by Django 5.0.9 on 2024-10-24 12:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitles',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
